// <auto-generated />
using System;
using JevMcp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JevMcp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921194108_AddCallLogCostUsd")]
    partial class AddCallLogCostUsd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("JevMcp.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("JevMcp.Data.CallLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Instant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultingAction")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenPrefix")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Instant");

                    b.HasIndex("Tool");

                    b.ToTable("CallLogs", (string)null);
                });

            modelBuilder.Entity("JevMcp.Data.McpAccessToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("AccessTokens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
