<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JevMcp.Providers\JevMcp.Providers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="JevMcp.App" />
    <InternalsVisibleTo Include="JevMcp.Tests" />
  </ItemGroup>

</Project>
